### ISSUE TITLE
Problems installing fonts [LemonBar]

### ISSUE THREAD

**Issue by DevGrohl** [electro7/dotfiles#1]
Current distribution: ArchLinux

Tried:
-Installed powerline to get fonts
-Installed terminus
-Installed terminusicons2

I'm surprised that I'm the first having problems with the fonts, I tried installing terminus, terminusicons2, and many many more, but I cant make the icons and some other features in lemonbar work.

![2015-09-08-23 49 57_1366x768_scrot](https://cloud.githubusercontent.com/assets/4367399/9753576/5580389e-5684-11e5-9fc7-6da232bc1114.png)

Im not very good in eyecandy topics, so I don't know if its important that I can't see the icons in the github code as you can see in the picture.

**Comment by karlosos** [comment]
Have you added font path with "xset fp+ <path>"?

```
xset fp+ $HOME/.fonts/misc
xset fp+ $HOME/.fonts/ohsnap
xset fp+ $HOME/.fonts/terminesspowerline
```

**Comment by DevGrohl** [comment]
xset fp+ $HOME/.fonts/misc
xset fp+ $HOME/.fonts/ohsnap
xset fp+ $HOME/.fonts/terminesspowerline

This solved it, i didnt knew how to charge the fonts, but I'm having problems to keep the changes...

Tried so far:
xset fp rehash
fc-cache -vf

Thank you!

**Comment by nakami** [comment]
i have the same problem.
i tried running the xset commands in a batch script. xset wants the display, and doesn't work simply if you run such a script via crontab or similiar.

why don't we just convert the fonts to TTF-format?
