### ISSUE TITLE
font issues & workspace names

### ISSUE THREAD

**Issue by t0m5k1** [electro7/dotfiles#12]
Seems like the main gripe with this great i3 theme/layout is the fonts.
Every start up we need to issue:

xset fp+ $HOME/.fonts/misc
xset fp+ $HOME/.fonts/ohsnap
xset fp+ $HOME/.fonts/terminesspowerline
pkill i3_lemonbar.sh
then restart i3

placing the above in the config does not work

also to compound things further I have issues with my workspace names.
I use unicode fonts that are found in the "Private use area" of many popular fonts:

 , , , , , , , , , 

It would appear that the parser, config font or something else is not liking these & the workspaces just remain blank:

![screenshot_2016-03-10_21-56-00](https://cloud.githubusercontent.com/assets/1597399/13685928/0124b078-e70b-11e5-84a0-906212182af3.png)

other than using 1-0 a-z I don't know how to fix this.

Please help

**Comment by demure** [comment]
Are you naming a workspace "1 ", or "1", as it doesn't like the spaces.
https://notabug.org/demure/dotfiles/src/master/i3/lemonbar/demure_i3_lemonbar_mod.png
https://notabug.org/demure/dotfiles/src/master/i3/config#L36-L47

**Comment by t0m5k1** [comment]
No the number you see in the image is for testing.
There is no number prefixing the workspace name, these are my work space names from my config:

```
set $ws1 
set $ws2 
set $ws3 
set $ws4 
set $ws5 
set $ws6 
set $ws7 
set $ws8 
set $ws9 
set $ws10 
```

They work fine in a normal i3 config, this "theme/layout" is not detecting the unicode font & leaving it blank, all the bindings/assigns for each work space still function (as that part is i3 not the script or lemonbar)

**Comment by t0m5k1** [comment]
hmmm upon visiting your repo I am now thinking yours is more toward my liking  :)
I see you font line is a lot easier to understand, I take it it is also easier to configure?

**Comment by demure** [comment]
I've made a number of mods/tweaks that I wanted :)
The font bit is due to my use of [krypt-n/bar](https://github.com/krypt-n/bar), which can do xft (Thank goodness!).

I try to account for most of my tweaks in my [readme](https://notabug.org/demure/dotfiles/src/master/i3/lemonbar/README.md). ^_^

**Comment by t0m5k1** [comment]
I still have the exact same issue even when I use demure dotfiles!
Is it that this just refuses to parse any font from the "private use area" ??
I get the same errors which leads me to believe it is an issue with the python/perl workspace script as it seems to be that which gets the error.

**Comment by jarhat** [comment]
This question is bothering me too!
I hope we all can finally have icons as workspace names :).. I'm on it!

**Comment by jarhat** [comment]
... by the way.. I had it .. only with the misc/terminusicons2mono.bdf ones.. 
In i3_lemonbar_parser.sh within the workspace section is I just replaced a '${1#???}' with '%{T2}${icon_home}' and here we go..

![img-2016-04-11-232811](https://cloud.githubusercontent.com/assets/13524127/14443102/7688d89e-003d-11e6-91c8-37b9abbfdeb9.png)

.. but this would only work with electro7's patched misc/terminusicons2mono.bdf.
I was trying to get more of these kind of glyphs from the siji font here on github
(see https://github.com/gstk/siji ), but I couldn't make it yet..

An approach on how to create these kind of fonts would be nice..
Electro7 wrote on reddit that he patched the misc/terminusicons2mono.bdf himself.
I have no idea on how to get this done.. like basically chuck some siji glyphs in there?!?

**Comment by electro7** [comment]
It's only work with misc/terminusicons2mono.bdf patched version. Sorry.
