### ISSUE TITLE
Trouble with 'make' in instructions

### ISSUE THREAD

**Issue by dutyqueen** [electro7/dotfiles#13]
Hello,
Thank you for putting together such a lovely i3wm arrangement.

I'm new to using i3wm although I've followed a few tutorials.

For some reason when I get to the tail end of the lemonbar installation as per your instructions, the make command returns the following:

lilqueen@dutyqueen:~/tmp$ make
make: **\* No targets specified and no makefile found.  Stop.

Any help would be greatly appreciated.

Thanks,

_S

**Comment by ghost** [comment]
cd into bar, then do make.

**Comment by dutyqueen** [comment]
Tino,

Thanks for the prompt response!

This worked. I have made and compiled everything. Then I copied the text
from your .i3/config into mine. When I then refresh the config, and have
also restarted the machine to ensure I restarted lightdm, etc.

After that, I'm not able to see the bar, the workspaces, etc. Not sure if I
should have copied more files or configurations from github or what I
should do. Again forgive my newbieness, but from that git repository what
else am I supposed to download? I see already in the home folder your
dotfiles directory. However in your repository there are more directories
(eg .fonts) that I do not have. Sill all of these be required to run your
i3 setup? If so what is the proper way to pull those files? When I
'download zip' it provides just the dotfiles directory which I already had
installed.

Again, thank you for the suppport!

**Comment by ghost** [comment]
You might want to follow the instructions to install the dotfiles. In short lines, clean install of the system, then delete all your files from $HOME (rm -rf *) and then use "git clone https://github.com/electro7/dotfiles ." or in this case the dotfiles with my changes "git clone https://github.com/tinnotl/dotfiles ."

I hope I helped you.

**Comment by dutyqueen** [comment]
I created a brand new user to have a sandbox environment in which to
experiment. Yes I did remove all files from the $HOME path and used git
clone as specified. Perhaps I have some more learning to do on my own to
get this up and running as I can't understand what might be going wrong or
what is missing... I do appreciate your support!

**Comment by dutyqueen** [comment]
Also I responded using email and didn't realize it attached my signatures. Oops..
