### ISSUE TITLE
Fonts+LemonBar not Working

### ISSUE THREAD

**Issue by ymarcus93** [electro7/dotfiles#14]
The custom lemonbar is not working for me. I added the fonts and have the correct commands in my i3 configuration to add the fonts, yet the bar keeps on looking weird. It also doesn't show any of my workspaces.

Here is what it looks like: [Screenshot](http://i.imgur.com/Vn9221s.png)

Does anyone else have this problem or have a solution?

**Comment by ymarcus93** [comment]
I seem to be making progress, as seen [here](http://i.imgur.com/JoDSnQs.png), but the font still looks choppy and my workspaces don't show up.

**Comment by t0m5k1** [comment]
what are your workspaces in the normal i3 config?

**Comment by ymarcus93** [comment]
```
# Workspace Variables
set $ws1 1
set $ws2 2
set $ws3 3
set $ws4 4
set $ws5 5
set $ws6 6
set $ws7 7
set $ws8 8
set $ws9 9
set $ws10 10
```

**Comment by t0m5k1** [comment]
odd I thought perhaps you used a list of pictorial fonts like mine but as the list is just numbers makes you wonder if the perl & python parsers are broken.
Also considering the last time electro7 did anything to this repo makes me wonder if we are alone in this & will need to attempt to fix it ourselves!!

**Comment by ymarcus93** [comment]
Yes, I think something is wrong with the i3_workspaces python script. When I run it myself, I get the following:

```
[yuval@arch lemonbar]$ python i3_workspaces.py
Traceback (most recent call last):
  File "i3_workspaces.py", line 22, in <module>
    import i3
ImportError: No module named 'i3'
[yuval@arch lemonbar]$ python i3_workspaces.pl
  File "i3_workspaces.pl", line 18
    use strict;
             ^
SyntaxError: invalid syntax
```

**Comment by ymarcus93** [comment]
Whoops...forgot to install i3-py. After installing it, the i3_workspaces.py script works and returns the following when I have two workspaces open:
`WSPINA1 FOC2`

Even though the script works, still the workspace names do not show up in the bar. I only see the window name from xprop.

**Comment by zacknorman** [comment]
@ymarcus93 I'm stuck on the first step, my bar still looks like your first screenshot... How did you get it from the first to the second? Thanks mate!

**Comment by demure** [comment]
@zacknorman If you continue to have issues, you might like to try my version https://notabug.org/demure/dotfiles/src/master/i3/lemonbar

**Comment by t0m5k1** [comment]
I still get the same issue with your's Demure. Something is not liking the use of pictorial fonts which results in workspace.pl/py ignoring the names of the workspaces. I can replicate with both

**Comment by zacknorman** [comment]
@demure Im going to give yours a try, I'll let ya know, cheers!

**Comment by leifmadsen** [comment]
I have this in my `.xsession` which is what made my bar load the fonts correctly:

```
# load up the fonts
xset fp+ $HOME/.fonts/misc
xset fp+ $HOME/.fonts/ohsnap
xset fp+ $HOME/.fonts/terminesspowerline
xset fp+ $HOME/.fonts/tewi
fc-cache -v
```

**Comment by electro7** [comment]
The reply of leifmadsen is correct. xset fp+ in .xsession is mandatory.

**Comment by khlj** [comment]
@zacknorman Also try to install i3-py, xorg-xlsfonts. And if you have conky --version -gt 1.9, there is a lua script in the repo named `convert.lua` you can use to convert. If having a different conky version was the case, you would also have to edit the parser and i3_lemonbar.sh to avoid showing %% instead of %.

**Comment by Capuno** [comment]
@ymarcus93 how did you made to fix the first problem? I'm having the same issue the icons look as letters and I have boxes instead of arrows

**Comment by xxxperimental** [comment]
I've got the same issue as @zacknorman and @Capuno, my lemonbar looks exactly like the one on the first screenshot.

**Comment by Capuno** [comment]
@xxxperimental I solved it with 3 lines on my ~/.i3/config (or ~/.config/i3/config):

`exec xset fp+ /home/capuno/.fonts/misc`
`exec xset fp+ /home/capuno/.fonts/ohsnap`
`exec xset fp+ /home/capuno/.fonts/terminesspowerline`

**Comment by leifmadsen** [comment]
@Capuno isn't this what I said here? :)  https://github.com/electro7/dotfiles/issues/14#issuecomment-238226914
