### ISSUE TITLE
Battery Indicator

### ISSUE THREAD

**Issue by ymarcus93** [electro7/dotfiles#15]
Does anyone know how I can add a battery indicator to the lemonbar? What files do I need to edit?

**Comment by demure** [comment]
You can use conky to do this. I have a conky entry in my [fork](https://notabug.org/demure/dotfiles/src/master/i3/lemonbar), but have moved to acpi files with awk as my Thinkpad X260 has two batteries that need to be averaged.

My set up has chagned the original conky order, so both the [conky](https://notabug.org/demure/dotfiles/src/master/i3/lemonbar/i3_lemonbar_conky#L31-L32) and the [i3_lemonbar_parser.sh](https://notabug.org/demure/dotfiles/src/master/i3/lemonbar/i3_lemonbar_parser.sh#L79-L116) need to be eddited. I also added settings to [i3_lemonbar_config](https://notabug.org/demure/dotfiles/src/master/i3/lemonbar/i3_lemonbar_config).

If you care about the Thinkpad solution, you can read through my fork.

**Comment by electro7** [comment]
Sorry, I have no laptop. With conky is easy to do it as demure indicates.
