### ISSUE TITLE
bincode explanation

### ISSUE THREAD

**Issue by kannaiah** [electro7/dotfiles#17]
I'm unable to map bin codes to keys.
I'm suing UK key board but I could not understand what the bincodes mean.

I was able to figureout $mod+24 -> q (quit) but other I'm not.
Could you tell me how I can find the mappings

**Comment by kannaiah** [comment]
I was able to get keycodes using 
`xmodmap -pk`

**Comment by electro7** [comment]
Yes, here is in I3 user's guide -> ( https://i3wm.org/docs/userguide.html#keybindings)
