### ISSUE TITLE
Lemonbar disappears after logout and login

### ISSUE THREAD

**Issue by krypttr** [electro7/dotfiles#19]
Hello,

Thanks for amazing dotfiles. I've problem with lemonbar. Whenever I logout and relogin lemonbar disappears. A couple of i3_lemonbar.sh processes are listed as running however no other processes called by the script runs. I found out that whenever i3 runs the bar command 2 instances of i3_lemonbar.sh is listed under running processes. If I kill the second i3_lemonbar.sh process nothing happes to the bar however when I logout and log back in lemonbar appears and works as expected.  How can I solve this problem? Thank you!

**Comment by demure** [comment]
I modified my logout sequence to pkill lemonbar first. https://notabug.org/demure/dotfiles/src/master/i3/config#L185

**Comment by electro7** [comment]
Yes, use "pkill lemonbar; i3-msg exit" in logout sequence as demure do.
