### ISSUE TITLE
Title in the bar does not update automatically.

### ISSUE THREAD

**Issue by bl33pbl0p** [electro7/dotfiles#22]
The title in the powerline bar isn't updating automatically. For example: When I open a tab in Firefox, say, archlinux.org, it shows me the title correctly, but the title isnt updated when I open another tab and naviagte to a website. It does update when i switch to it again from another window. I hope I made my situation clear.

**Comment by bl33pbl0p** [comment]
An easier way to supply titles would be to use xtitle, which directly supplies the title, and updates it when a tab is changed, it also has a snoop mode (xtitle -s) similar to xprop's spy mode. here is the link: https://www.github.com/baskerville/xtitle

**Comment by bl33pbl0p** [comment]
@electro7

**Comment by electro7** [comment]
I haven't issues with title, and yes, you can use xtitle at alternative. 

Thanks!.
