### ISSUE TITLE
xrvt formatting and Font error

### ISSUE THREAD

**Issue by kelepon** [electro7/dotfiles#23]
Hello, i found error on xrvt formatting..

https://github.com/electro7/dotfiles/blob/master/.Xresources#L19

and 

https://github.com/electro7/dotfiles/blob/master/.Xresources#L134

renamed electro7 with the user name in home directory..

**Comment by electro7** [comment]
Thanks!

Now .Xresources is fixed. 

You need to specify the home directory with "xrdb -I$HOME".
