### ISSUE TITLE
Question: What is the role of the python script in lemonbar?

### ISSUE THREAD

**Issue by Xiaoming94** [electro7/dotfiles#26]
What purpose does the workspaces.py fulfil in .3/lemonbar/ ?

**Comment by t0m5k1** [comment]
It is what gets the workspace names so they can be displayed in the bar

**Comment by Xiaoming94** [comment]
I don't see it getting called, or referenced to in any script in the .i3 directory

**Comment by t0m5k1** [comment]
Try looking in the lemon bar scripts it is in there

**Comment by t0m5k1** [comment]
i3_lemonbar.sh:
```

# i3 Workspaces, "WSP"
# TODO : Restarting I3 breaks the IPC socket con. :(
$(dirname $0)/i3_workspaces.pl > "${panel_fifo}" &
```

Lines 22-24
alternatively you can replace line 24 with:
`$(dirname $0)/i3_workspaces.py > "${panel_fifo}" &`

**Comment by electro7** [comment]
Is another version ot workspaces listing. I use the perl script, but you can use the python script, or delete the file. ;)
