### ISSUE TITLE
Lemonbar weird characters?

### ISSUE THREAD

**Issue by secnice** [electro7/dotfiles#29]
Trying to get it running on i3 and it looks like i am missing a font of some sort and i just can't figure this out.

i3 config file:

bar {
    i3bar_command ~/eletro7/.i3/lemonbar/i3_lemonbar.sh 
}

Im getting this weird characters:
https://ibb.co/etTj7z

Would anyone shed some light on it?

**Comment by MarlieChiller-Home** [comment]
i am also getting this even though i have awesome fonts and terminus fonts installed

**Comment by demure** [comment]
I recommend using a version of lemonbar that supposts xft, it will likely make it easier to get your fontawesome working.
