### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by justintv90** [electro7/dotfiles#5]
Your setting is so amazing but i cant understand your language. Can you translate it into English, thanks so much.

**Comment by ttepatti** [comment]
I have a modified and almost completely English version of this config on my Github, but be warned, some features have been removed (I didn't use any of the email notifications, mpd, or weechat, etc)

https://github.com/ttepatti/LinuxConfig

I don't mind translating each comment though and merging it with the main branch, though. I'd be more than happy to if electro7 doesn't mind

**Comment by electro7** [comment]
Sorry, my english is very basic. Only for little use and computer terminology. I attempt to do the guides in english but the result is poor. Sorry.
