### ISSUE TITLE
100% CPU on i3_workspaces.pl [LemonBar]

### ISSUE THREAD

**Issue by sheoak** [electro7/dotfiles#8]
After some time (30min/1hour) i3_workspaces.pl uses 100% of CPU. My computer is not that fast but my previous configuration using conky was working fine. 

The xsession_errors log contains some repeated errors, no idea if it's related:

`Wide character in print at ~/bin/lemonbar/i3_workspaces.pl line 130`

**Comment by ymarcus93** [comment]
I'm having the same problem. At 100%

**Comment by electro7** [comment]
I think I correct this bug few months ago.
